### ISSUE TITLE
Add index page

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/NexusHub#157]
**I'm submitting a...**

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

<br>

**Current behavior**

There's literally no index page.

<br>

**Expected behavior**

There should be an index page that doesn't redirect to the warframe page.
Content-wise we'd still just have to guide users to the warframe page, 
because there's nothing else right now. But maybe if there's enough
time, we could also write some information on the whole rework and
how that happened.

In any case, it needn't anything special, it's gonna get overhauled
several times after the rework anyways.

<br>

**Minimal reproduction of the problem**

This is kind of 'duh'

<br>

**Environment**

Browser: 
- [ ] Chrome (desktop) version:
- [ ] Chrome (Android) version:
- [ ] Chrome (iOS) version:
- [ ] Firefox version:
- [ ] Safari (desktop) version:
- [ ] Safari (iOS) version:
- [ ] IE version:
- [ ] Edge version:

For development issues:
- Node version:
- Operating System:

##

**Additional Description**

**Comment by Nakroma** [comment]
First, very basic version exists now
