### ISSUE TITLE
Silva & Aegis page won't load

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/NexusHub#197]
**I'm submitting a...**

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

<br>

**Current behavior**

The page won't load.

<br>

**Expected behavior**

The page should load.

<br>

**Minimal reproduction of the problem**

Run the stack, try to search for "Silva & Aegis Prime"

<br>

**Environment**

Browser: 
- [ ] Chrome (desktop) version:
- [ ] Chrome (Android) version:
- [ ] Chrome (iOS) version:
- [ ] Firefox version:
- [ ] Safari (desktop) version:
- [ ] Safari (iOS) version:
- [ ] IE version:
- [ ] Edge version:

For development issues:
- Node version:
- Operating System:

##

**Additional Description**

This is very very likely to be happening because of encoding issues from the nexus url name to the actual API name. For instance `frost-prime` would be `Frost Prime` on the API. Same thing here, except it messed up somewhere.

**Comment by TobiTenno** [comment]
`&` not getting uri encoded, maybe?

**Comment by Nakroma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix: some items with strange characters dont load correctly](https://trello.com/c/i2JqXNSj/30-fix-some-items-with-strange-characters-dont-load-correctly)
