### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Rycieos** [nexus-devs/NexusHub#35]
The codebase doesn't have a license, contributing information, or copying information. Providing those would allow for contributions from others, if the team is open to it.

**Comment by Kaptard** [comment]
Check the [development branch](https://github.com/nexus-devs/nexus-stats/tree/development). We use a permissive non-commercial license there. The main branch is outdated anyway. 
We're definitely open to contributions of any kind. Lots of issues still open.

**Comment by Rycieos** [comment]
Thanks for that.

Maybe change the development branch to be the default, so first time users see the up-to-date README and LICENSE?

**Comment by Kaptard** [comment]
Good point, went ahead and changed that 👌
