### ISSUE TITLE
Add option to at the same time view both sellers and buyers of an item

### ISSUE THREAD

**Issue by k4far** [nexus-devs/NexusHub#97]
**I'm submitting a...**

- [ ] Bug report
- [X] Feature request
- [ ] Documentation issue or request

<br>

**Current behavior**

You can only see one type of offers, so you have to switch from one to the other which isn't really convenient if you are trading professionally.

<br>

**Expected behavior**

Split available space used by one type between both sellers and buyers and use it as extra view option.

1. Currently it's like this:

[BUYERS] (active window), [SELLERS] (click me)
*content

2. Optional view I have in mind:
BUYERS | SELLERS
content | content

3. Final result could be like this:
[BUYERS] (active window), [SELLERS] (click me), [BOTH] (click me).

<br>

For development issues:
- Node version: "Unifying Warframe's Marketplace" Project.

##

**Additional Description**

It would come in handy for those who are selling their wares using bull & bear strategies. Especially useful when you are buying/selling in bulk. It would greatly increase comfort after moving out from the in-game trading chat entirely.

**Comment by Kaptard** [comment]
Both sellers and buyers are displayed simultaneously now. Not gonna add a buying/selling button because that may confuse people with the buying/selling for the orders list.
